In [11]:
import pandas

df = pandas.read_csv("odot_hwy_26_crashes_2019.csv")
df

,Crash ID,Record Type,Vehicle ID,Participant ID,Participant Display Seq#,Vehicle Coded Seq#,Participant Vehicle Seq#,Serial #,Crash Month,Crash Day,...,Participant Cause 2 Code,Participant Cause 3 Code,Participant Event 1 Code,Participant Event 2 Code,Participant Event 3 Code,BAC Test Results Code,Alcohol Use Reported,Drug Use Reported,Participant Marijuana Use Reported,Participant Striker Flag
0,1809119,1,NaN,NaN,NaN,NaN,NaN,99992.0,3.0,14.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1809119,2,3409578.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1809119,3,3409578.0,3887884.0,1.0,1.0,1.0,NaN,NaN,NaN,...,NaN,0.0,9.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
3,1809119,2,3409579.0,NaN,NaN,2.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1809119,3,3409579.0,3887885.0,2.0,2.0,1.0,NaN,NaN,NaN,...,NaN,NaN,9.0,9.0,0.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2734,1860771,1,NaN,NaN,NaN,NaN,NaN,1465.0,5.0,6.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2735,1860771,2,3503992.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2736,1860771,3,3503992.0,3991482.0,1.0,1.0,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN
2737,1860771,2,3503993.0,NaN,NaN,2.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2738,1860771,3,3503993.0,3991483.0,2.0,2.0,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN

In [12]:
crashdf = df[df['Record Type'] == 1]
crashdf

,Crash ID,Record Type,Vehicle ID,Participant ID,Participant Display Seq#,Vehicle Coded Seq#,Participant Vehicle Seq#,Serial #,Crash Month,Crash Day,...,Participant Cause 2 Code,Participant Cause 3 Code,Participant Event 1 Code,Participant Event 2 Code,Participant Event 3 Code,BAC Test Results Code,Alcohol Use Reported,Drug Use Reported,Participant Marijuana Use Reported,Participant Striker Flag
0,1809119,1,NaN,NaN,NaN,NaN,NaN,99992.0,3.0,14.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,1809229,1,NaN,NaN,NaN,NaN,NaN,2405.0,3.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,1809637,1,NaN,NaN,NaN,NaN,NaN,1811.0,5.0,17.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,1810874,1,NaN,NaN,NaN,NaN,NaN,99981.0,4.0,7.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,1812266,1,NaN,NaN,NaN,NaN,NaN,5970.0,7.0,8.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2716,1860371,1,NaN,NaN,NaN,NaN,NaN,3344.0,4.0,19.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2719,1860417,1,NaN,NaN,NaN,NaN,NaN,3385.0,4.0,20.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2724,1860427,1,NaN,NaN,NaN,NaN,NaN,3396.0,4.0,13.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2729,1860453,1,NaN,NaN,NaN,NaN,NaN,3423.0,4.0,22.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2734,1860771,1,NaN,NaN,NaN,NaN,NaN,1465.0,5.0,6.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
vehicdf = df[df['Record Type'] == 2]
vehicdf

,Crash ID,Record Type,Vehicle ID,Participant ID,Participant Display Seq#,Vehicle Coded Seq#,Participant Vehicle Seq#,Serial #,Crash Month,Crash Day,...,Participant Cause 2 Code,Participant Cause 3 Code,Participant Event 1 Code,Participant Event 2 Code,Participant Event 3 Code,BAC Test Results Code,Alcohol Use Reported,Drug Use Reported,Participant Marijuana Use Reported,Participant Striker Flag
1,1809119,2,3409578.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1809119,2,3409579.0,NaN,NaN,2.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,1809229,2,3409765.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,1809637,2,3410470.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,1810874,2,3412622.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2727,1860427,2,3503379.0,NaN,NaN,2.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2730,1860453,2,3503423.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2732,1860453,2,3503424.0,NaN,NaN,2.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2735,1860771,2,3503992.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2737,1860771,2,3503993.0,NaN,NaN,2.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
partidf = df[df['Record Type'] == 3]
partidf

,Crash ID,Record Type,Vehicle ID,Participant ID,Participant Display Seq#,Vehicle Coded Seq#,Participant Vehicle Seq#,Serial #,Crash Month,Crash Day,...,Participant Cause 2 Code,Participant Cause 3 Code,Participant Event 1 Code,Participant Event 2 Code,Participant Event 3 Code,BAC Test Results Code,Alcohol Use Reported,Drug Use Reported,Participant Marijuana Use Reported,Participant Striker Flag
2,1809119,3,3409578.0,3887884.0,1.0,1.0,1.0,NaN,NaN,NaN,...,NaN,0.0,9.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
4,1809119,3,3409579.0,3887885.0,2.0,2.0,1.0,NaN,NaN,NaN,...,NaN,NaN,9.0,9.0,0.0,NaN,NaN,NaN,NaN,NaN
7,1809229,3,3409765.0,3888073.0,1.0,1.0,1.0,NaN,NaN,NaN,...,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
8,1809229,3,0.0,3888074.0,2.0,NaN,1.0,NaN,NaN,NaN,...,NaN,0.0,9.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN
11,1809637,3,3410470.0,3888766.0,1.0,1.0,1.0,NaN,NaN,NaN,...,NaN,0.0,9.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2728,1860427,3,3503379.0,3990896.0,2.0,2.0,1.0,NaN,NaN,NaN,...,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
2731,1860453,3,3503423.0,3990937.0,1.0,1.0,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN
2733,1860453,3,3503424.0,3990938.0,2.0,2.0,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN
2736,1860771,3,3503992.0,3991482.0,1.0,1.0,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN
2738,1860771,3,3503993.0,3991483.0,2.0,2.0,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN

In [91]:
crashdf = crashdf.dropna(axis='columns', how='all')
crashdf

,Crash ID,Record Type,Serial #,Crash Month,Crash Day,Crash Year,Week Day Code,Crash Hour,County Code,City Section ID,...,Total Pedestrian Count,Total Pedestrian Fatality Count,Total Pedestrian Non-Fatal Injury Count,Total Pedalcyclist Count,Total Pedalcyclist Fatality Count,Total Pedalcyclist Non-Fatal Injury Count,Total Unknown Non-Motorist Count,Total Unknown Non-Motorist Fatality Count,Total Unknown Non-Motorist Injury Count,Total Vehicle Occupant Count
0,1809119,1,99992.0,3.0,14.0,2019.0,5.0,14.0,26.0,0.0,...,0.0,0.0,0.0,0.0,0.0,3.0,3.0,2.0,0.0,1.0
5,1809229,1,2405.0,3.0,3.0,2019.0,1.0,2.0,3.0,185.0,...,0.0,0.0,0.0,0.0,0.0,1.0,2.0,1.0,0.0,0.0
9,1809637,1,1811.0,5.0,17.0,2019.0,6.0,99.0,3.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0
12,1810874,1,99981.0,4.0,7.0,2019.0,1.0,0.0,26.0,245.0,...,0.0,0.0,0.0,0.0,0.0,1.0,2.0,1.0,0.0,0.0
16,1812266,1,5970.0,7.0,8.0,2019.0,2.0,14.0,26.0,245.0,...,0.0,0.0,0.0,0.0,0.0,5.0,5.0,2.0,0.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2716,1860371,1,3344.0,4.0,19.0,2019.0,6.0,20.0,26.0,245.0,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0
2719,1860417,1,3385.0,4.0,20.0,2019.0,7.0,15.0,26.0,245.0,...,0.0,0.0,0.0,0.0,0.0,4.0,4.0,4.0,0.0,0.0
2724,1860427,1,3396.0,4.0,13.0,2019.0,7.0,21.0,26.0,245.0,...,0.0,0.0,0.0,0.0,0.0,4.0,4.0,3.0,0.0,1.0
2729,1860453,1,3423.0,4.0,22.0,2019.0,2.0,12.0,26.0,245.0,...,0.0,0.0,0.0,0.0,0.0,2.0,2.0,2.0,0.0,0.0
2734,1860771,1,1465.0,5.0,6.0,2019.0,2.0,15.0,3.0,185.0,...,0.0,0.0,0.0,0.0,0.0,2.0,2.0,1.0,0.0,1.0

In [90]:
vehicdf = vehicdf.dropna(axis='columns', how='all')
vehicdf

,Crash ID,Record Type,Vehicle ID,Vehicle Coded Seq#,Total Count of Persons Involved,Total Persons Using Safety Equipment,Total Persons Not Using Safety Equipment,Total Persons Safety Equipment Use Unknown,Vehicle Ownership Code,Vehicle Special Use Code,...,Vehicle Action Code,Vehicle Cause 1 Code,Vehicle Cause 2 Code,Vehicle Cause 3 Code,Vehicle Event 1 Code,Vehicle Event 2 Code,Vehicle Event 3 Code,Vehicle Exceeded Posted Speed Flag,Vehicle Hit & Run Flag,Safety Equipment Used Quantity
1,1809119,2,3409578.0,1.0,1.0,0.0,9.0,0.0,0.0,1.0,...,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0,1.0,1.0
3,1809119,2,3409579.0,2.0,1.0,0.0,1.0,0.0,0.0,3.0,...,NaN,NaN,NaN,0.0,0.0,1.0,0.0,1.0,2.0,0.0
6,1809229,2,3409765.0,1.0,1.0,0.0,4.0,0.0,1.0,1.0,...,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0,1.0,1.0
10,1809637,2,3410470.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,...,62.0,10.0,NaN,0.0,0.0,1.0,0.0,0.0,1.0,1.0
13,1810874,2,3412622.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,...,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2727,1860427,2,3503379.0,2.0,0.0,0.0,1.0,0.0,9.0,6.0,...,NaN,NaN,NaN,0.0,0.0,3.0,0.0,0.0,3.0,0.0
2730,1860453,2,3503423.0,1.0,0.0,0.0,1.0,0.0,9.0,1.0,...,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0,1.0,1.0
2732,1860453,2,3503424.0,2.0,0.0,0.0,1.0,0.0,9.0,6.0,...,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0,1.0,0.0
2735,1860771,2,3503992.0,1.0,0.0,0.0,1.0,0.0,9.0,3.0,...,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0,1.0,1.0
2737,1860771,2,3503993.0,2.0,0.0,0.0,1.0,0.0,9.0,1.0,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,1.0,1.0,0.0

In [89]:
partidf = partidf.dropna(axis=1, how='all')
partidf

,Crash ID,Record Type,Vehicle ID,Participant ID,Participant Display Seq#,Vehicle Coded Seq#,Participant Vehicle Seq#,Safety Equipment Un-used Quantity,Safety Equipment Use Unknown Quantity,Vehicle Occupant Count,...,Non-Motorist Travel Direction To,Non-Motorist Location,Participant Action,Participant Error 1 Code,Participant Error 2 Code,Participant Error 3 Code,Participant Cause 3 Code,Participant Event 1 Code,Participant Event 2 Code,Participant Event 3 Code
2,1809119,3,3409578.0,3887884.0,1.0,1.0,1.0,1.0,0.0,0.0,...,NaN,NaN,1.0,NaN,NaN,NaN,0.0,9.0,0.0,0.0
4,1809119,3,3409579.0,3887885.0,2.0,2.0,1.0,1.0,0.0,0.0,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,9.0,9.0,0.0
7,1809229,3,3409765.0,3888073.0,1.0,1.0,1.0,1.0,0.0,0.0,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0
8,1809229,3,0.0,3888074.0,2.0,NaN,1.0,3.0,0.0,0.0,...,NaN,NaN,18.0,NaN,NaN,NaN,0.0,9.0,1.0,0.0
11,1809637,3,3410470.0,3888766.0,1.0,1.0,1.0,1.0,0.0,0.0,...,81.0,NaN,1.0,NaN,NaN,NaN,0.0,9.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2728,1860427,3,3503379.0,3990896.0,2.0,2.0,1.0,1.0,0.0,0.0,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0
2731,1860453,3,3503423.0,3990937.0,1.0,1.0,1.0,1.0,0.0,0.0,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0
2733,1860453,3,3503424.0,3990938.0,2.0,2.0,1.0,1.0,0.0,0.0,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0
2736,1860771,3,3503992.0,3991482.0,1.0,1.0,1.0,1.0,0.0,0.0,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0
2738,1860771,3,3503993.0,3991483.0,2.0,2.0,1.0,1.0,0.0,0.0,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0

In [18]:
df.columns.values.tolist()

['Crash ID',
 'Record Type',
 'Vehicle ID',
 'Participant ID',
 'Participant Display Seq#',
 'Vehicle Coded Seq#',
 'Participant Vehicle Seq#',
 'Serial #',
 'Crash Month',
 'Crash Day',
 'Crash Year',
 'Week Day Code',
 'Crash Hour',
 'County Code',
 'City Section ID',
 'Urban Area Code',
 'Functional Class Code',
 'NHS Flag',
 'Highway Number',
 'Highway Suffix',
 'Roadway Number',
 'Highway Component',
 'Mileage Type',
 'Connection Number',
 'Linear Reference System (LRS)',
 'Latitude Degrees',
 'Latitude Minutes',
 'Latitude Seconds',
 'Longitude Degrees',
 'Longitude Minutes',
 'Longitude Seconds',
 'Latitude (Decimal Degrees)',
 'Longitude (Decimal Degrees)',
 'Special Jurisdiction',
 'Jurisdiction Group',
 'Street Number',
 'Nearest Intersecting Street Number',
 'Intersection Sequence Number',
 'Distance from Intersection',
 'Direction From Intersection',
 'Milepoint',
 'Posted Speed Limit',
 'Road Character',
 'Off Roadway Flag',
 'Intersection Type',
 'Intersection Related Flag',
 'Roundabout Flag',
 'Driveway Related Flag',
 'Number of Lanes',
 'Number of Turning Legs',
 'Median Type',
 'Impact Location',
 'Crash Type',
 'Collision Type',
 'Crash Severity',
 'Weather Condition',
 'Road Surface Condition',
 'Light Condition',
 'Traffic Control Device (TCD)',
 'TCD Functional Flag',
 'Investigating Agency',
 'Crash Level Event 1 Code',
 'Crash Level Event 2 Code',
 'Crash Level Event 3 Code',
 'Crash Level Cause 1 Code',
 'Crash Level Cause 2 Code',
 'Crash Level Cause 3 Code',
 'School Zone Indicator',
 'Work Zone Indicator',
 'Secondary Crash Indicator',
 'Alcohol-Involved Flag',
 'Drugs Involved Flag',
 'Crash Marijuana Involved Flag',
 'Speed Involved Flag',
 'Crash Level Hit & Run Flag',
 'Population Range Code',
 'Road Control',
 'Route Type',
 'Route Number',
 'Region ID',
 'District ID',
 'Segment Marker ID',
 'Segment Point LRS Measure',
 'Unlocatable Flag',
 'Total Vehicle Count',
 'Total Fatality Count',
 'Total Suspected Serious Injury (A) Count',
 'Total Suspected Minor Injury (B) Count',
 'Total Possible Injury (C) Count',
 'Total Non-Fatal Injury Count',
 'Total Un-Injured  Children Age 00-04',
 'Total Un-Injured Persons',
 'Total Pedestrian Count',
 'Total Pedestrian Fatality Count',
 'Total Pedestrian Non-Fatal Injury Count',
 'Total Pedalcyclist Count',
 'Total Pedalcyclist Fatality Count',
 'Total Pedalcyclist Non-Fatal Injury Count',
 'Total Unknown Non-Motorist Count',
 'Total Unknown Non-Motorist Fatality Count',
 'Total Unknown Non-Motorist Injury Count',
 'Total Vehicle Occupant Count',
 'Total Count of Persons Involved',
 'Total Persons Using Safety Equipment  ',
 'Total Persons Not Using Safety Equipment',
 'Total Persons Safety Equipment Use Unknown',
 'Vehicle Ownership Code',
 'Vehicle Special Use Code',
 'Vehicle Type Code',
 'Emergency Use Flag',
 'Number of Trailers',
 'Vehicle Movement Code',
 'Vehicle Travel Direction From',
 'Vehicle Travel Direction To',
 'Vehicle Action Code',
 'Vehicle Cause 1 Code',
 'Vehicle Cause 2 Code',
 'Vehicle Cause 3 Code',
 'Vehicle Event 1 Code',
 'Vehicle Event 2 Code',
 'Vehicle Event 3 Code',
 'Vehicle Exceeded Posted Speed Flag',
 'Vehicle Hit & Run Flag',
 'Safety Equipment Used Quantity',
 'Safety Equipment Un-used Quantity',
 'Safety Equipment Use Unknown Quantity',
 'Vehicle Occupant Count',
 'Vehicle Striking Flag',
 'Participant Type Code',
 'Participant Hit & Run Flag',
 'Public Employee Flag',
 'Sex',
 'Age',
 'Driver License Status',
 'Driver Residence Status',
 'Injury Severity',
 'Participant Safety Equipment Use Code',
 'Airbag Deployment',
 'Non-Motorist Movement Code',
 'Non-Motorist Travel Direction From',
 'Non-Motorist Travel Direction To',
 'Non-Motorist Location',
 'Participant Action',
 'Participant Error 1 Code',
 'Participant Error 2 Code',
 'Participant Error 3 Code',
 'Participant Cause 1 Code',
 'Participant Cause 2 Code',
 'Participant Cause 3 Code',
 'Participant Event 1 Code',
 'Participant Event 2 Code',
 'Participant Event 3 Code',
 'BAC Test Results Code',
 'Alcohol Use Reported',
 'Drug Use Reported',
 'Participant Marijuana Use Reported',
 'Participant Striker Flag']

In [66]:
assertion = "Assertion: Every vehicle has a unique Vehicle ID"
original_list = vehicdf['Vehicle ID'].tolist()
unique_list = set(original_list)
assert len(original_list) == len(unique_list), "Every vehicle does not have a unique Vehicle ID"
print(f"{assertion} PASSED")

Assertion: Every vehicle has a unique Vehicle ID PASSED

In [65]:
assertion = "Assertion: Every crash has a unique Crash ID"
original_list = crashdf['Crash ID'].tolist()
unique_list = set(original_list)
assert len(original_list) == len(unique_list), "Every crash does not have a unique Crash ID"
print(f"{assertion} PASSED")

Assertion: Every crash has a unique Crash ID PASSED

In [62]:
assertion = "Assertion: Every crash occurred in some county"
assert all(crashdf['County Code']), "Not all crash record has county data"
print(f"{assertion} PASSED")

Assertion: Every crash occurred in some county PASSED

In [59]:
assertion = "Assertion: Every crash has a DMV Crash Serial Number"
assert all(crashdf['Serial #']), "Not all crash record has a serial number"
print(f"{assertion} PASSED")

Assertion: Every crash has a DMV Crash Serial Number PASSED

In [68]:
assertion = "Assertion: Crashes are evenly distributed throughout the months of the year"
crash_month_df = crashdf.groupby(['Crash Month']).count()[['Crash ID']]
print(crash_month_df)
print(crash_month_df.describe())
std = crash_month_df.describe().loc['std', 'Crash ID']
if std < 5:
    print(f"{assertion} PASSED")
else:
    print(f"{assertion} FAILED")
print(f"The standard deviation of crashes in each month is {std}")

             Crash ID
Crash Month
1.0                56
2.0                46
3.0                57
4.0                53
5.0                41
6.0                36
7.0                37
8.0                33
9.0                34
10.0               36
11.0               35
12.0               44
        Crash ID
count  12.000000
mean   42.333333
std     8.804269
min    33.000000
25%    35.750000
50%    39.000000
75%    47.750000
max    57.000000
Assertion: Crashes are evenly distributed throughout the months of the year FAILED
The standard deviation of crashes in each month is 8.804268937007292

In [20]:
assertion = "Assertion: There were thousands of crashes but not millions"
assert len(crashdf) < 1000000, "There were at least a million crashes"
assert len(crashdf) < 10000, "There were tens of thousands of crashes"
print(f"{assertion} PASSED")

Assertion: There were thousands of crashes but not millions PASSED

In [21]:
assertion = "Assertion: Every vehicle listed in the crash data was part of a known crash"
crash_ids = crashdf['Crash ID'].tolist()
for i in range(0, len(vehicdf)):
    if not vehicdf.iloc[i]['Crash ID'] in crash_ids:
        print(f"{assertion} FAILED")
        break
    else:
        print(f"{assertion} PASSED")
        break

Assertion: Every vehicle listed in the crash data was part of a known crash PASSED

In [22]:
assertion = "Assertion: Every crash with a latitude must have a longitude"
rows_failed_assert = []
for i in range(0, len(crashdf)):
    if not crashdf.iloc[i]['Latitude Degrees'] and crashdf.iloc[i]['Longitude Degrees']:
        rows_failed_assert.append(crashdf.iloc[i])
if len(rows_failed_assert) == 0:
    print(f"{assertion} PASSED")
else:
    print(f"{assertion} FAILED")

Assertion: Every crash with a latitude must have a longitude PASSED

In [23]:
assertion = "Assertion: Every crash occurred during year 2019"
crash_in_year = crashdf['Crash Year'] == 2019
count = 0
for n in crash_in_year:
    if n == False:
        count += 1
if count == 0:
    print(f"{assertion} PASSED")
else:
    print(f"{assertion} FAILED")

Assertion: Every crash occurred during year 2019 PASSED

In [24]:
assertion = "Assertion: Every crash occurred on a date"
crash_has_month = crashdf['Crash Month'].tolist()
crash_has_day = crashdf['Crash Day'].tolist()
crash_has_year = crashdf['Crash Year'].tolist()
if all(crash_has_month) and all(crash_has_day) and all(crash_has_year):
    print(f"{assertion} PASSED")
else:
    print(f"{assertion} FAILED")

Assertion: Every crash occurred on a date PASSED

In [92]:
crashdf.to_csv("odot_hwy_26_crashes_2019_crashdf.csv", index=False)
vehicdf.to_csv("odot_hwy_26_crashes_2019_vehicdf.csv", index=False)
partidf.to_csv("odot_hwy_26_crashes_2019_partidf.csv", index=False)